from __future__ import annotations

from sim2real.config.robots.base import RobotCfg


KHAN_JOINT_NAMES = (
    "Left_hip_pitch_joint",
    "Left_hip_roll_joint",
    "Left_hip_yaw_joint",
    "Left_knee_joint",
    "Left_ankle_pitch_joint",
    "Left_ankle_roll_joint",
    "Right_hip_pitch_joint",
    "Right_hip_roll_joint",
    "Right_hip_yaw_joint",
    "Right_knee_joint",
    "Right_ankle_pitch_joint",
    "Right_ankle_roll_joint",
    "waist_yaw_joint",
    "Left_shoulder_pitch_joint",
    "Left_shoulder_roll_joint",
    "Left_shoulder_yaw_joint",
    "Left_elbow_joint",
    "Left_wrist_roll_joint",
    "Left_wrist_yaw_joint",
    "Right_shoulder_pitch_joint",
    "Right_shoulder_roll_joint",
    "Right_shoulder_yaw_joint",
    "Right_elbow_joint",
    "Right_wrist_roll_joint",
    "Right_wrist_yaw_joint",
    "Neck_yaw_joint",
    "Neck_pitch_joint",
)

# Body names copied from the MuJoCo XML exactly (case-sensitive).
KHAN_BODY_NAMES = (
    "base_link",
    "Left_hip_pitch_Link",
    "Left_hip_roll_Link",
    "Left_hip_yaw_Link",
    "Left_knee_Link",
    "Left_ankle_pitch_Link",
    "Left_ankle_roll_Link",
    "Right_hip_pitch_Link",
    "Right_hip_roll_Link",
    "Right_hip_yaw_Link",
    "Right_knee_Link",
    "Right_ankle_pitch_Link",
    "Right_ankle_roll_Link",
    "waist_yaw_Link",
    "Left_shoulder_pitch_Link",
    "Left_shoulder_roll_Link",
    "Left_shoulder_yaw_Link",
    "Left_elbow_Link",
    "Left_wrist_roll_Link",
    "Left_wrist_yaw_Link",
    "Right_shoulder_pitch_Link",
    "Right_shoulder_roll_Link",
    "Right_shoulder_yaw_Link",
    "Right_elbow_Link",
    "Right_wrist_roll_Link",
    "Right_wrist_yaw__Link",
    "Neck_yaw_Link",
    "Neck_pitch_Link",
)

KHAN_JOINT_POS_LOWER_LIMIT = {
    "Left_hip_pitch_joint": -1.9198,
    "Left_hip_roll_joint": -0.5236,
    "Left_hip_yaw_joint": -2.0071,
    "Left_knee_joint": -0.3490,
    "Left_ankle_pitch_joint": -0.5236,
    "Left_ankle_roll_joint": -0.3490,
    "Right_hip_pitch_joint": -1.9198,
    "Right_hip_roll_joint": -0.5236,
    "Right_hip_yaw_joint": -2.0071,
    "Right_knee_joint": -0.3490,
    "Right_ankle_pitch_joint": -0.5236,
    "Right_ankle_roll_joint": -0.3490,
    "waist_yaw_joint": -2.0071,
    "Left_shoulder_pitch_joint": -1.5707,
    "Left_shoulder_roll_joint": -1.9189,
    "Left_shoulder_yaw_joint": -1.5707,
    "Left_elbow_joint": -0.8726,
    "Left_wrist_roll_joint": -1.5707,
    "Left_wrist_yaw_joint": 0.0,
    "Right_shoulder_pitch_joint": -1.5707,
    "Right_shoulder_roll_joint": -1.9189,
    "Right_shoulder_yaw_joint": -1.5707,
    "Right_elbow_joint": -0.8726,
    "Right_wrist_roll_joint": -1.5707,
    "Right_wrist_yaw_joint": 0.0,
    "Neck_yaw_joint": -1.5707,
    "Neck_pitch_joint": -0.6108,
}

KHAN_JOINT_POS_UPPER_LIMIT = {
    "Left_hip_pitch_joint": 1.2217,
    "Left_hip_roll_joint": 2.3562,
    "Left_hip_yaw_joint": 3.5779,
    "Left_knee_joint": 2.2689,
    "Left_ankle_pitch_joint": 0.6108,
    "Left_ankle_roll_joint": 0.3490,
    "Right_hip_pitch_joint": 1.2217,
    "Right_hip_roll_joint": 3.5779,
    "Right_hip_yaw_joint": 3.5779,
    "Right_knee_joint": 2.2689,
    "Right_ankle_pitch_joint": 0.6108,
    "Right_ankle_roll_joint": 0.3490,
    "waist_yaw_joint": 3.5779,
    "Left_shoulder_pitch_joint": 1.5707,
    "Left_shoulder_roll_joint": 1.9189,
    "Left_shoulder_yaw_joint": 1.5707,
    "Left_elbow_joint": 2.2689,
    "Left_wrist_roll_joint": 1.5707,
    "Left_wrist_yaw_joint": 1.5707,
    "Right_shoulder_pitch_joint": 1.5707,
    "Right_shoulder_roll_joint": 1.9189,
    "Right_shoulder_yaw_joint": 1.5707,
    "Right_elbow_joint": 2.2689,
    "Right_wrist_roll_joint": 1.5707,
    "Right_wrist_yaw_joint": 1.5707,
    "Neck_yaw_joint": 1.5707,
    "Neck_pitch_joint": 0.6108,
}

KHAN_JOINT_VELOCITY_LIMIT = {
    "Left_hip_pitch_joint": 32.0,
    "Left_hip_roll_joint": 32.0,
    "Left_hip_yaw_joint": 32.0,
    "Left_knee_joint": 20.0,
    "Left_ankle_pitch_joint": 37.0,
    "Left_ankle_roll_joint": 37.0,
    "Right_hip_pitch_joint": 32.0,
    "Right_hip_roll_joint": 32.0,
    "Right_hip_yaw_joint": 32.0,
    "Right_knee_joint": 20.0,
    "Right_ankle_pitch_joint": 37.0,
    "Right_ankle_roll_joint": 37.0,
    "waist_yaw_joint": 32.0,
    "Left_shoulder_pitch_joint": 37.0,
    "Left_shoulder_roll_joint": 37.0,
    "Left_shoulder_yaw_joint": 37.0,
    "Left_elbow_joint": 37.0,
    "Left_wrist_roll_joint": 37.0,
    "Left_wrist_yaw_joint": 22.0,
    "Right_shoulder_pitch_joint": 37.0,
    "Right_shoulder_roll_joint": 37.0,
    "Right_shoulder_yaw_joint": 37.0,
    "Right_elbow_joint": 37.0,
    "Right_wrist_roll_joint": 37.0,
    "Right_wrist_yaw_joint": 22.0,
    "Neck_yaw_joint": 22.0,
    "Neck_pitch_joint": 22.0,
}

# Approximated from the XML actuatorfrcrange values.
KHAN_JOINT_EFFORT_LIMIT = {
    "Left_hip_pitch_joint": 120.0,
    "Left_hip_roll_joint": 120.0,
    "Left_hip_yaw_joint": 120.0,
    "Left_knee_joint": 120.0,
    "Left_ankle_pitch_joint": 96.0,
    "Left_ankle_roll_joint": 96.0,
    "Right_hip_pitch_joint": 120.0,
    "Right_hip_roll_joint": 120.0,
    "Right_hip_yaw_joint": 120.0,
    "Right_knee_joint": 120.0,
    "Right_ankle_pitch_joint": 96.0,
    "Right_ankle_roll_joint": 96.0,
    "waist_yaw_joint": 120.0,
    "Left_shoulder_pitch_joint": 96.0,
    "Left_shoulder_roll_joint": 96.0,
    "Left_shoulder_yaw_joint": 36.0,
    "Left_elbow_joint": 36.0,
    "Left_wrist_roll_joint": 8.0,
    "Left_wrist_yaw_joint": 8.0,
    "Right_shoulder_pitch_joint": 96.0,
    "Right_shoulder_roll_joint": 96.0,
    "Right_shoulder_yaw_joint": 36.0,
    "Right_elbow_joint": 36.0,
    "Right_wrist_roll_joint": 8.0,
    "Right_wrist_yaw_joint": 8.0,
    "Neck_yaw_joint": 8.0,
    "Neck_pitch_joint": 8.0,
}

KHAN_JOINT_ARMATURE = {
    "Left_hip_pitch_joint": 0.03,
    "Left_hip_roll_joint": 0.03,
    "Left_hip_yaw_joint": 0.03,
    "Left_knee_joint": 0.03,
    "Left_ankle_pitch_joint": 0.016,
    "Left_ankle_roll_joint": 0.016,
    "Right_hip_pitch_joint": 0.03,
    "Right_hip_roll_joint": 0.03,
    "Right_hip_yaw_joint": 0.03,
    "Right_knee_joint": 0.03,
    "Right_ankle_pitch_joint": 0.016,
    "Right_ankle_roll_joint": 0.016,
    "waist_yaw_joint": 0.03,
    "Left_shoulder_pitch_joint": 0.016,
    "Left_shoulder_roll_joint": 0.016,
    "Left_shoulder_yaw_joint": 0.01,
    "Left_elbow_joint": 0.01,
    "Left_wrist_roll_joint": 0.01,
    "Left_wrist_yaw_joint": 0.01,
    "Right_shoulder_pitch_joint": 0.016,
    "Right_shoulder_roll_joint": 0.016,
    "Right_shoulder_yaw_joint": 0.01,
    "Right_elbow_joint": 0.01,
    "Right_wrist_roll_joint": 0.01,
    "Right_wrist_yaw_joint": 0.01,
    "Neck_yaw_joint": 0.01,
    "Neck_pitch_joint": 0.01,
}

KHAN_JOINT_FRICTIONLOSS = {
    joint_name: 0.01 for joint_name in KHAN_JOINT_NAMES
}

# qpos = [root xyz(3), root quat(4), 27 joint positions]
KHAN_DEFAULT_QPOS = (
    0.0,
    0.0,
    0.8,
    1.0,
    0.0,
    0.0,
    0.0,
    -0.2,
    0.0,
    0.0,
    0.4,
    -0.2,
    0.0,
    -0.2,
    0.0,
    0.0,
    0.4,
    -0.2,
    0.0,
    0.0,
    -1.57,
    1.57,
    0.3,
    0.0,
    0.0,
    -1.57,
    1.57,
    0.3,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
)

KHAN_CFG = RobotCfg(
    name="khan",
    joint_names=KHAN_JOINT_NAMES,
    body_names=KHAN_BODY_NAMES,
    joint_pos_lower_limit=KHAN_JOINT_POS_LOWER_LIMIT,
    joint_pos_upper_limit=KHAN_JOINT_POS_UPPER_LIMIT,
    joint_velocity_limit=KHAN_JOINT_VELOCITY_LIMIT,
    joint_effort_limit=KHAN_JOINT_EFFORT_LIMIT,
    joint_armature=KHAN_JOINT_ARMATURE,
    joint_frictionloss=KHAN_JOINT_FRICTIONLOSS,
    mjcf_path="deploy/Khan_mini_simplified/Khan_mini_simplified_new_bigfeet.xml",
    default_qpos=KHAN_DEFAULT_QPOS,
    publish_hz=50.0,
    domain_id=0,
    interface="eth0",
    mocap_ip="localhost",
    root_joint_names=("base_joint",),
    viewer_track_body_names=("base_link",),
    elastic_band_attach_body_names=("waist_yaw_Link", "base_link"),
)

__all__ = ["KHAN_CFG"]
